package kiinse.plugins.ggo.gungalewiki.enums;

import kiinse.plugins.ggo.gungaleapi.api.files.filemanager.YamlKeys;

public enum Config implements YamlKeys {
    PLAYER_HEAD_CMD,
    BUTTON_BACK_MATERIAL,
    BUTTON_LASTCRAFTS_MATERIAL,
    BUTTON_BOOKMARKS_MATERIAL,
    BUTTON_NEXTPAGE_MATERIAL,
    BUTTON_PREVPAGE_MATERIAL,
    BUTTON_HOME_MATERIAL,
    BUTTON_BACK_CMD,
    BUTTON_LASTCRAFTS_CMD,
    BUTTON_BOOKMARKS_CMD,
    BUTTON_NEXTPAGE_CMD,
    BUTTON_PREVPAGE_CMD,
    BUTTON_HOME_CMD,
    MENU_LASTCRAFTS_NAME,
    MENU_MAIN_NAME,
    MENU_FROMITEM_NAME,
    MENU_THISITEM_NAME,
    MENU_BOOKMARKS_NAME,
    DB_HOST,
    DB_PORT,
    DB_LOGIN,
    DB_PASSWORD,
    DB_NAME
}
